/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pwr_mnk_CppPlayer */

#ifndef _Included_pwr_mnk_CppPlayer
#define _Included_pwr_mnk_CppPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pwr_mnk_CppPlayer
 * Method:    randomCpp
 * Signature: ([[C)[I
 */
JNIEXPORT jintArray JNICALL Java_pwr_mnk_CppPlayer_randomCpp
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
